name: deploy-to-strato
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy-to-strato:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Setup ssh
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ssh.strato.de >> ~/.ssh/known_hosts
      - name: Check dir
        run: ls ${{ github.workspace }}
      - name: Copy files
        run: rsync -a ${{ github.workspace }} ${{ secrets.USER_IP }}:/portfolio-website
